name: Maven Continuous Integration

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request_ubuntu_java11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 11
        uses: actions/setup-java@v1
        with: 
          java-version: 1.11
      - name: Cache Maven Packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run JUnit
        run: mvn test --file pom.xml
  
  test_pull_request_ubuntu_java8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 8
        uses: actions/setup-java@v1
        with: 
          java-version: 1.8
      - name: Cache Maven Packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run JUnit
        run: mvn test --file pom.xml
        
  test_pull_request_windows_java11:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 11
        uses: actions/setup-java@v1
        with: 
          java-version: 1.11
      - name: Cache Maven Packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run JUnit
        run: mvn test --file pom.xml

  test_pull_request_windows_java8:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 8
        uses: actions/setup-java@v1
        with: 
          java-version: 1.8
      - name: Cache Maven Packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run JUnit
        run: mvn test --file pom.xml
        
  test_pull_request_mac_java11:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 11
        uses: actions/setup-java@v1
        with: 
          java-version: 1.11
      - name: Cache Maven Packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run JUnit
        run: mvn test --file pom.xml

  test_pull_request_mac_java8:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up JDK 8
        uses: actions/setup-java@v1
        with: 
          java-version: 1.8
      - name: Cache Maven Packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run JUnit
        run: mvn test --file pom.xml

  update_javadoc:
    needs: [test_pull_request_ubuntu_java11, test_pull_request_ubuntu_java8, test_pull_request_windows_java11, test_pull_request_windows_java8, test_pull_request_mac_java11, test_pull_request_mac_java8]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven Packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Generate JavaDoc
        run: mvn javadoc:javadoc
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Updated JavaDoc" -a
      - name: Push changes back to repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
